# Generated by Django 5.1.6 on 2025-05-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_hooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='status',
            new_name='state',
        ),
    ]
