# Generated by Django 5.1.6 on 2025-05-06 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_hooks', '0002_rename_status_conversation_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='user_id',
        ),
    ]
