# Generated by Django 5.1.6 on 2025-05-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_hooks', '0003_remove_conversation_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='direction_message',
        ),
        migrations.AddField(
            model_name='message',
            name='direction',
            field=models.CharField(blank=True, choices=[('sent', 'Sent'), ('received', 'Received')], max_length=10, null=True),
        ),
    ]
