# Generated by Django 5.1.6 on 2025-05-07 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_hooks', '0004_remove_message_direction_message_message_direction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='state',
            new_name='status',
        ),
    ]
